-- auto-generated definition
create table t_user
(
    id           bigint generated by default as identity
        primary key,
    uuid         varchar(64)  not null,
    gender       smallint,
    nick_name    varchar(64),
    mobile       varchar(64),
    username     varchar(128),
    email        varchar(128),
    password     varchar(256) not null,
    birthday     timestamp,
    avatar_url   varchar(256),
    status       smallint,
    point        bigint,
    gmt_create   bigint,
    gmt_modified bigint,
    balance      double precision,
    roles        varchar(32)
);

comment on column t_user.id is '主键';

comment on column t_user.uuid is '用户识别码';

comment on column t_user.gender is '性别0女1男';

comment on column t_user.nick_name is '昵称';

comment on column t_user.mobile is '手机号';

comment on column t_user.username is '用户名';

comment on column t_user.email is '邮箱';

comment on column t_user.password is '密码';

comment on column t_user.birthday is '生日';

comment on column t_user.avatar_url is '头像地址';

comment on column t_user.status is '用户状态0正常-1禁用';

comment on column t_user.point is '会员积分';

comment on column t_user.gmt_create is '创建时间';

comment on column t_user.gmt_modified is '修改时间';

comment on column t_user.balance is '用户余额';

comment on column t_user.roles is '角色权限--role_sys_superAdmin,role_sys_admin,role_common_user';

alter table t_user
    owner to postgres;

create unique index uuid
    on t_user (uuid);

create unique index username
    on t_user (username);

create unique index mobile
    on t_user (mobile);

create unique index email
    on t_user (email);

